name: Luciole
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: 16.0
  developmentLanguage: en

settings:
  base:
    PRODUCT_NAME: Luciole
    PRODUCT_BUNDLE_IDENTIFIER: com.example.Luciole
    SWIFT_VERSION: 5.0
    TARGETED_DEVICE_FAMILY: 2
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
    SUPPORTS_MACCATALYST: NO
    SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
    ENABLE_PREVIEWS: YES
    INFOPLIST_FILE: Luciole/Info.plist
    CODE_SIGN_ENTITLEMENTS: Luciole/Luciole.entitlements
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
    INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    INFOPLIST_KEY_UIRequiresFullScreen: YES
    INFOPLIST_KEY_UIStatusBarHidden: YES
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown"
    GENERATE_INFOPLIST_FILE: NO

targets:
  Luciole:
    type: application
    platform: iOS
    deploymentTarget: "16.0"

    sources:
      - path: Luciole
        excludes:
          - "*.md"
          - "*.sh"
          - "project.yml"

    entitlements:
      path: Luciole/Luciole.entitlements

    info:
      path: Luciole/Info.plist

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.Luciole
        INFOPLIST_FILE: Luciole/Info.plist
        CODE_SIGN_ENTITLEMENTS: Luciole/Luciole.entitlements
        TARGETED_DEVICE_FAMILY: 2
        IPHONEOS_DEPLOYMENT_TARGET: 16.0
        SWIFT_VERSION: 5.0
        ENABLE_PREVIEWS: YES

    scheme:
      testTargets: []
      gatherCoverageData: false

schemes:
  Luciole:
    build:
      targets:
        Luciole: all
    run:
      config: Debug
    archive:
      config: Release
